/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

plugins {
    `java`
    id("org.openstreetmap.josm") version "0.8.2"
}

version = "v0.0.1"
base.archivesBaseName = "gcsenabler"
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

josm {
    pluginName = "gcsenabler"
    josmCompileVersion = "18646"
    manifest {
        description = "Adds support for adding imagery layers hosted on Google Cloud Storage"
        mainClass = "org.openstreetmap.josm.plugins.gcsenabler.GCSImageryEnablerPlugin"
        minJosmVersion = "18646"
        author = "ramSeraph"
        includeLinksToGithubReleases = true
        // loadEarly = true
        // loadPriority = -1
        website = uri("https://github.com/ramSeraph/josm-gcs-imagery-enabler").toURL()
    }
    github {
        repositoryName = "josm-gcs-imagery-enabler"
        repositoryOwner = "ramSeraph"
        targetCommitish = "main"
    }
}
